### ISSUE TITLE
WASM: wasm streaming compile failed

### ISSUE THREAD

**Issue by marcusturewicz** [marcusturewicz/jsonvalidate.net#27]
Javascript console error when loading deployed website:
```
blazor.webassembly.js:1 WASM: wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.
d.printErr @ blazor.webassembly.js:1
(anonymous) @ mono.js:1
Promise.then (async)
createWasm @ mono.js:1
Module.asm @ mono.js:1
(anonymous) @ mono.js:1
blazor.webassembly.js:1 WASM: falling back to ArrayBuffer instantiation
```

**Comment by marcusturewicz** [comment]
Still happening

**Comment by marcusturewicz** [comment]
Fixed

**Comment by pablopalma** [comment]
How did you resolve?

**Comment by marcusturewicz** [comment]
www.jsonvalidate.net is deployed as a static website on Azure Storage with Azure CDN. I'm using Azure Pipelines to copy the static files to Azure Storage. However, the copy function was not applying the correct mime type for the `mono.wasm` file, causing the above error. So I had to manually set the mime type for this file. Apologies, my traceability wasn't very good on this issue as I still don't have my release pipeline as code yet (tracked in #35). I'll try to get that fixed soon. In the meantime, here is a screenshot of the UI for that step:
![image](https://user-images.githubusercontent.com/24448509/65000248-3e646280-d92e-11e9-93f9-77f0bb1fb8c0.png)


or if you prefer YAML code:
```yaml
steps:
- task: AzureFileCopy@2
  displayName: 'wasm copy and set content type'
  inputs:
    SourcePath: '$(System.DefaultWorkingDirectory)/_marcusturewicz.jsonvalidate.net/drop/JsonValidate/JsonValidate/dist/_framework/wasm/mono.wasm'
    azureSubscription: 'Pay-As-You-Go (REDACTED)'
    Destination: AzureBlob
    storage: jsonvalidate
    ContainerName: '$web'
    BlobPrefix: '_framework/wasm'
    AdditionalArgumentsForBlobCopy: '/Y /Z /V /SetContentType:"application/wasm"'
```
